<script setup lang="ts">
import { ref, watch } from "vue";
import Panel from "../components/Panel.vue";
import { session } from "../lib/session";
import type { Device } from "../../../service/src/vault/model";
const { snapshot, busy, visibility } = session;
const adding = ref(false);
const name = ref("");
const id = ref("");
const publicKey = ref("");
const clientId = ref("");
const renaming = ref<Device>();
const rename = ref("");
const target = ref<Device>();
const hard = ref(false);
const password = ref("");
watch(visibility, () => {
  password.value = "";
  target.value = undefined;
});
async function enroll() {
  if (await session.enroll(name.value, id.value, publicKey.value, clientId.value)) {
    adding.value = false;
    name.value = "";
    id.value = "";
    publicKey.value = "";
    clientId.value = "";
  }
}
async function confirmRevoke() {
  if (!target.value) return;
  const value = password.value;
  password.value = "";
  const success = hard.value
    ? await session.rotate(value, target.value.id)
    : await session.revoke(target.value.id);
  if (success) target.value = undefined;
}
async function saveName() {
  if (renaming.value && (await session.rename(renaming.value.id, rename.value)))
    renaming.value = undefined;
}
</script>
<template>
  <div class="page-heading">
    <div>
      <h1>
        Devices
        <span class="count">{{
          snapshot?.devices.filter((d) => d.status === "active").length
        }}</span>
      </h1>
    </div>
    <button class="primary" :disabled="busy" @click="adding = true">+ Register CLI device</button>
  </div>
  <div class="table-card table-scroll">
    <table>
      <thead>
        <tr>
          <th>Device</th>
          <th>Type</th>
          <th>Status</th>
          <th>Registered</th>
          <th class="actions-heading">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="device in snapshot?.devices" :key="device.id">
          <td>
            <strong>{{ device.name }}</strong
            ><small class="mono muted block">{{ device.id }}</small>
          </td>
          <td>
            <span class="subtle-badge">{{
              device.type === "cli" ? "CLI · read-only" : "Browser"
            }}</span>
          </td>
          <td>
            <span class="badge" :class="{ neutral: device.status === 'revoked' }">{{
              device.status
            }}</span>
          </td>
          <td class="muted nowrap">{{ new Date(device.created_at).toLocaleDateString() }}</td>
          <td class="actions">
            <button
              @click="
                renaming = device;
                rename = device.name;
              "
            >
              Rename</button
            ><button
              v-if="device.status === 'active'"
              class="danger-text"
              @click="
                target = device;
                hard = false;
              "
            >
              Revoke
            </button>
          </td>
        </tr>
        <tr v-if="!snapshot?.devices.length">
          <td colspan="5" class="empty">No trusted devices.</td>
        </tr>
      </tbody>
    </table>
  </div>
  <Panel v-if="adding" title="Register CLI device" @close="adding = false"
    ><form @submit.prevent="enroll">
      <label>Name<input v-model="name" required maxlength="128" placeholder="Work laptop" /></label
      ><label
        >Device ID<input
          v-model="id"
          required
          placeholder="UUID generated by the CLI"
          spellcheck="false"
          class="mono" /></label
      ><label
        >Public key<input
          v-model="publicKey"
          required
          minlength="43"
          maxlength="43"
          placeholder="Base64url X25519 public key"
          spellcheck="false"
          class="mono" /></label
      ><label
        >Access Client ID<input
          v-model="clientId"
          required
          placeholder="… .access"
          spellcheck="false"
          class="mono"
      /></label>
      <p class="hint">
        Use the CLI's public enrollment details and its manually provisioned Access Client ID. Never
        enter a private key or token secret.
      </p>
      <div class="form-actions">
        <button type="button" @click="adding = false">Cancel</button
        ><button class="primary" :disabled="busy">Register device</button>
      </div>
    </form></Panel
  >
  <Panel v-if="renaming" title="Rename device" @close="renaming = undefined"
    ><form @submit.prevent="saveName">
      <label>Name<input v-model="rename" required maxlength="128" /></label>
      <div class="form-actions">
        <button type="button" @click="renaming = undefined">Cancel</button
        ><button class="primary" :disabled="busy">Save name</button>
      </div>
    </form></Panel
  >
  <Panel
    v-if="target"
    title="Revoke device"
    @close="
      target = undefined;
      password = '';
    "
    ><form @submit.prevent="confirmRevoke">
      <p>
        Revoke <strong>{{ target.name }}</strong
        >?
      </p>
      <label class="check"><input v-model="hard" type="checkbox" />Rotate the vault key too</label>
      <p class="hint">
        {{
          hard
            ? "Re-encrypts all secrets for the remaining devices. Previously copied secrets cannot be retracted."
            : "Blocks future API access and removes this device’s wrapped key."
        }}
      </p>
      <label v-if="hard"
        >Master password<input
          v-model="password"
          type="password"
          autocomplete="current-password"
          required
      /></label>
      <div class="form-actions">
        <button
          type="button"
          @click="
            target = undefined;
            password = '';
          "
        >
          Cancel</button
        ><button class="danger" :disabled="busy">
          {{ busy ? "Working…" : hard ? "Revoke and rotate" : "Revoke device" }}
        </button>
      </div>
    </form></Panel
  >
</template>
